# Generated by Django 3.1 on 2020-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
