# Generated by Django 3.1 on 2020-09-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_item_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
