# Generated by Django 3.1 on 2020-09-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200930_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_details',
            field=models.TextField(null=True),
        ),
    ]
