# Generated by Django 3.1.2 on 2020-10-02 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_vote_vote_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_items',
        ),
        migrations.AddField(
            model_name='item',
            name='poll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='vote',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='vote.vote'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(0, '单选公开'), (1, '单选不公开'), (2, '多选公开'), (3, '多选不公开')]),
        ),
    ]
