# Generated by Django 3.1.2 on 2020-10-02 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20201002_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vote',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vote.vote'),
        ),
    ]
